`define QUARTER_NOTE 2'd0
`define HALF_NOTE 2'd1
`define WHOLE_NOTE 2'd2
`define NOTE_WIDTH 28
`define NOTE_HEIGHT 24
`define STEM_LINES 3
`define STEM_ATTACH_HEIGHT 4
`define STEM_WIDTH 3
`define DOT_WIDTH 8